  # This workflow will run when integration has passed. It installs dependencies, and runs pyinstaller on the source
  # files to create a single binary executable for Windows.
  # For more information see: https://github.com/marketplace/actions/pyinstaller-windows

name: python_deploy

on:
  workflow_run:
    workflows: ["python_integrate"]
    branches: [master]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcodegen
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./

      - uses: actions/upload-artifact@v2
        with:
          name: QR-codengrave
          path: ./src/dist/windows
